/* Shared UI and prototype data. No build tools, imports, or server required. */
'use strict';
const S = window.S = {};
S.base = document.body.dataset.section === 'instructor' ? '../' : '';
S.url = path => S.base + path;
S.get = (key, fallback=null) => { try { const raw=localStorage.getItem(key); return raw===null?fallback:JSON.parse(raw); } catch { return fallback; } };
S.set = (key,value) => { try { localStorage.setItem(key,JSON.stringify(value)); return true; } catch { S.toast('Storage is unavailable or full. Try a smaller image or enable browser storage.'); return false; } };
S.esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
S.money = n => 'Rp'+Number(n||0).toLocaleString('id-ID');
S.date = value => new Date(value+'T00:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
S.day = n => {const d=new Date(); d.setDate(d.getDate()+n);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
S.id = () => window.crypto?.randomUUID ? crypto.randomUUID() : Date.now().toString(36)+Math.random().toString(36).slice(2,8);
S.categories=['Design','Programming','Music','Photography','Business','Marketing','Language','Cooking'];
S.icons=['◈','⌘','♫','◎','↗','✦','文','♧'];
if(S.get('sessionExpires') && Date.now()>S.get('sessionExpires'))localStorage.removeItem('user');
S.user=()=>S.get('user'); S.uid=()=>S.user()?.id||'guest';
S.owned=(key)=>S.get(key,[]).filter(x=>x.userId===S.uid());
S.all=()=>[...S.get('classes',[]),...S.get('createdClasses',[])];
S.find=id=>S.all().find(c=>c.id===id);
S.mine=()=>S.get('createdClasses',[]).filter(c=>c.ownerId===S.uid());
S.selected=()=>S.find(new URLSearchParams(location.search).get('id'));
// Upgrade stock artwork at render time, preserving stored classes and custom uploads.
S.image=c=>{
if(c.image?.startsWith('data:image/'))return c.image;
const photos={Design:'design',Programming:'programming',Music:'guitar',Photography:'photo',Business:'business',Marketing:'marketing',Language:'language',Cooking:'cooking'};
if(!c.image||/^assets\/images\/class-\d+\.svg$/.test(c.image))return S.url('assets/images/'+(photos[c.category]||'hero')+'-v2.png');
return S.url(c.image);
};
S.toast=text=>{document.querySelector('.toast')?.remove();const t=document.createElement('div');t.className='toast';t.role='status';t.textContent=text;document.body.append(t);setTimeout(()=>t.remove(),4000);};
S.notify=text=>{const n=S.get('notifications',[]);n.unshift({id:S.id(),userId:S.uid(),text,date:new Date().toISOString(),read:false});S.set('notifications',n);};

S.mode=mode=>{if(!S.user()){location.href=S.url('login.html');return;}S.set('currentMode',mode);const u=S.user();u.mode=mode;S.set('user',u);const accounts=S.get('accounts',[]);const a=accounts.find(x=>x.id===u.id);if(a){a.mode=mode;S.set('accounts',accounts);}location.href=S.url(mode==='instructor'?'instructor/dashboard.html':'index.html');};
S.modal=(title,body)=>{document.querySelector('#info-dialog')?.remove();const d=document.createElement('dialog');d.id='info-dialog';d.className='modal';d.innerHTML=`<h2>${S.esc(title)}</h2>${body}<form method="dialog"><button class="btn full">Got it</button></form>`;document.body.append(d);d.showModal();};
if(!S.get('classes')){
const rows=[['figma','UI/UX Design with Figma','Sarah Putri','Design',75000,4.9,125,'Beginner','Online',0],['photo','Basic Photography','Andi Pratama','Photography',100000,4.8,89,'Beginner','Offline',1],['guitar','Beginner Guitar','Rizky Mahendra','Music',50000,4.9,64,'Beginner','Online',2],['python','Introduction to Python','Kevin Wijaya','Programming',125000,4.7,210,'Beginner','Online',3],['speaking','Public Speaking','Nadia Putri','Business',60000,4.8,98,'Intermediate','Offline',4],['marketing','Social Media That Connects','Dinda Lestari','Marketing',85000,4.8,76,'Intermediate','Online',5],['english','Everyday English Conversation','Maya Santoso','Language',65000,4.9,112,'Beginner','Online',6],['cooking','The Art of Indonesian Cooking','Bima Saputra','Cooking',150000,4.8,54,'Advanced','Offline',7]];
S.set('classes',rows.map((r,i)=>({id:r[0],title:r[1],instructor:r[2],category:r[3],price:r[4],rating:r[5],students:r[6],level:r[7],type:r[8],image:`assets/images/class-${r[9]}.svg`,date:S.day(i),time:'19:00',duration:90,sessions:1,capacity:15,filled:i===7?15:i+3,location:i%2?'Bandung':'Jakarta',address:'Creative Hub, Jl. Merdeka 12',platform:'Google Meet',status:'Active',createdAt:Date.now()-i*86400000,description:'Build practical skills through a friendly, hands-on session. Work on a real project, get personal feedback, and leave with the confidence to keep learning.',short:'A hands-on workshop for your next big step.',learn:['Understand the essential tools and techniques','Create a practical project from start to finish','Get personal feedback and a plan to keep improving'],requirements:'Bring your curiosity and a notebook. Online classes require a laptop and a stable internet connection.',bio:'An independent creative and experienced mentor who makes learning practical, welcoming, and fun.'})));
}
for(const k of ['createdClasses','enrollments','payments','reviews','bookmarks','notifications','accounts'])if(S.get(k)===null)S.set(k,[]);
if(!S.get('currentMode'))S.set('currentMode','learner');
S.reviews=id=>[...S.get('reviews',[]).filter(r=>r.classId===id),{name:'Nabila R.',rating:5,text:'Really practical and easy to follow. I loved the personal feedback!',date:S.day(-5)},{name:'Arif S.',rating:5,text:'A welcoming class with clear explanations. Excited to keep practicing.',date:S.day(-8)}];
S.reviewHTML=id=>S.reviews(id).map(r=>`<article class="review-card"><strong>${S.esc(r.name)}</strong> <span class="stars">${'★'.repeat(r.rating)}</span><p>${S.esc(r.text)}</p><small class="muted">${S.date(r.date)}${r.id?'':' · Sample review'}</small></article>`).join('');
S.card=c=>`<article class="card class-card" data-category="${S.esc(c.category)}"><a class="thumb" href="${S.url('class-detail.html')}?id=${encodeURIComponent(c.id)}"><img src="${S.image(c)}" alt="${S.esc(c.category)} workshop — illustrative AI-generated photo" loading="lazy"><span class="badge">${S.esc(c.category)}</span></a><div class="card-body"><div class="tiny muted">${S.esc(c.level)} <span aria-hidden="true">·</span> ${S.esc(c.type)}</div><h3><a href="${S.url('class-detail.html')}?id=${encodeURIComponent(c.id)}">${S.esc(c.title)}</a></h3><div class="instructor-line"><span class="instructor-initial" aria-hidden="true">${S.esc(c.instructor.split(' ').map(n=>n[0]).slice(0,2).join(''))}</span>${S.esc(c.instructor)} <span class="verified" title="${c.ownerId?'Community instructor':'Verified demo instructor'}">${c.ownerId?'':'✓'}</span></div><div class="card-meta"><span><span class="stars">★</span> ${c.rating||'New'}</span><span class="muted">(${c.students||0} students)</span></div><div class="tiny muted">◷ ${S.date(c.date)} · ${c.time}</div><div class="card-foot"><span class="price">${S.money(c.price)}</span><a class="btn small class-cta" href="${S.url('class-detail.html')}?id=${encodeURIComponent(c.id)}">View Class ↗</a></div></div></article>`;
S.empty=(title,text,href,label)=>`<div class="empty"><span class="mode-icon">◈</span><h3>${title}</h3><p>${text}</p>${href?`<a class="btn" href="${S.url(href)}">${label}</a>`:''}</div>`;
S.details=c=>`<img class="cover" src="${S.image(c)}" alt="${S.esc(c.category)} class — illustrative AI-generated photo"><div class="panel"><span class="badge">${S.esc(c.category)}</span><h1>${S.esc(c.title)}</h1><div class="card-meta"><span class="stars">★ ${c.rating||'New'}</span><span>${c.students||0} students</span><span>${S.esc(c.level)}</span><span>${S.esc(c.type)}</span></div><h2>About This Class</h2><p>${S.esc(c.description)}</p><h3>What You'll Learn</h3><ul class="checklist">${(c.learn||[]).map(x=>`<li>${S.esc(x)}</li>`).join('')}</ul><h3>Requirements</h3><p>${S.esc(c.requirements)}</p><h3>Class Schedule</h3><p>${S.date(c.date)} · ${c.time} · ${c.duration} minutes · ${c.sessions} session(s)</p><p>${c.type==='Offline'?S.esc(c.location+' — '+c.address):S.esc(c.platform)+' · Online workshop'}</p></div>`;
S.sidebar=()=>`<aside class="sidebar"><div class="eyebrow" style="padding:10px 16px">Your workspace</div>${[['dashboard','▦','Dashboard'],['my-classes','▤','My Classes'],['students','♙','Students'],['earnings','↗','Earnings']].map(([f,i,t])=>`<a class="${location.pathname.endsWith(f+'.html')?'active':''}" href="${S.url('instructor/'+f+'.html')}">${i} &nbsp; ${t}</a>`).join('')}<a href="${S.url('instructor/create-class.html')}">＋ Create New Class</a><a href="${S.url('profile.html')}">◎ &nbsp; Profile</a><div class="notice">Your skills can make someone's next big step.</div></aside>`;
function shell(){
const logged=!!S.user(), teach=document.body.dataset.section==='instructor';
const links=teach?[['instructor/dashboard.html','Dashboard'],['instructor/my-classes.html','My Classes'],['instructor/students.html','Students'],['instructor/earnings.html','Earnings']]:[['index.html','Home'],['explore.html','Explore Classes'],['how-it-works.html','How It Works']];
document.querySelector('#header').innerHTML=`<header class="header"><nav class="container nav" aria-label="Main navigation"><a class="logo" href="${S.url('index.html')}"><span class="logo-mark">⇄</span>SkillSwap<span style="color:var(--blue)">.</span></a><div class="navlinks" id="navlinks">${links.map(([f,t])=>`<a class="${location.pathname.endsWith(f)?'active':''}" href="${S.url(f)}">${t}</a>`).join('')}</div><div class="navright">${logged?`<select class="mode" aria-label="Switch mode"><option value="learner" ${!teach?'selected':''}>🎓 Learn Mode</option><option value="instructor" ${teach?'selected':''}>👨‍🏫 Teach Mode</option></select><a class="iconbtn optional" aria-label="Search classes" href="${S.url('explore.html')}">⌕</a><a class="iconbtn optional" aria-label="Notifications" href="${S.url('notifications.html')}">♧</a><a class="avatar" aria-label="Profile" href="${S.url('profile.html')}">${S.esc(S.user().name.slice(0,1))}</a>`:`<a href="${S.url('login.html')}">Log in</a><a class="btn small" href="${S.url('register.html')}">Sign up ↗</a>`}<button class="iconbtn mobile-toggle" aria-label="Open navigation" aria-expanded="false">☰</button></div></nav></header>`;
document.querySelector('.mode')?.addEventListener('change',e=>S.mode(e.target.value));
document.querySelector('.mobile-toggle').onclick=e=>{const open=document.querySelector('#navlinks').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open);};
document.querySelector('#footer').innerHTML=`<footer class="footer"><div class="container"><div class="footer-top"><div><a class="logo" href="${S.url('index.html')}"><span class="logo-mark">⇄</span>SkillSwap.</a><p class="tiny">A little learning. A world of possibilities.</p></div><div class="footer-links"><a href="${S.url('about.html')}">About</a><a href="${S.url('how-it-works.html')}">How It Works</a><a href="${S.url('help.html')}">Help</a><a href="${S.url('terms.html')}">Terms</a><a href="${S.url('privacy.html')}">Privacy</a></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} SkillSwap. Learn a Skill. Share a Skill.</span><span>Prototype · Illustrative AI-generated photography</span></div></div></footer>`;
}
shell();
document.addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(b)S.mode(b.dataset.mode);});
