'use strict';
(() => {
const page=document.body.dataset.page;
if(page==='choose-mode'){if(!S.user())location.replace('login.html');return;}
const form=document.querySelector('#auth-form'),error=document.querySelector('#auth-error');
function signIn(user,remember){const safe={...user};delete safe.password;S.set('user',safe);S.set('rememberMe',!!remember);S.set('sessionExpires',Date.now()+(remember?30*24:8)*3600000);S.set('currentMode',safe.mode||'learner');location.href=safe.mode?(safe.mode==='instructor'?'instructor/dashboard.html':'index.html'):'choose-mode.html';}
form.addEventListener('submit',e=>{e.preventDefault();error.textContent='';const d=Object.fromEntries(new FormData(form));const accounts=S.get('accounts',[]);
if(page==='register'){
if(d.password!==d.confirm){error.textContent='Passwords do not match.';return;}
if(accounts.some(a=>a.email.toLowerCase()===d.email.toLowerCase()||a.username.toLowerCase()===d.username.toLowerCase())){error.textContent='That email or username is already registered in this browser.';return;}
const user={id:S.id(),name:d.name.trim(),username:d.username,email:d.email,phone:d.phone,password:d.password,bio:'',skills:'',mode:null};
if(!S.set('accounts',[...accounts,user]))return;signIn(user,false);
}else{const user=accounts.find(a=>(a.email.toLowerCase()===d.identity.trim().toLowerCase()||a.username.toLowerCase()===d.identity.trim().toLowerCase())&&a.password===d.password);if(!user){error.textContent='Email, username, or password is incorrect. Register here or try the demo account.';return;}signIn(user,d.remember);}
});
function demo(){let accounts=S.get('accounts',[]);let user=accounts.find(a=>a.id==='demo-athira');if(!user){user={id:'demo-athira',name:'Athira Ramadhani',username:'athira',email:'athira@example.com',phone:'',password:'demo123',bio:'Designer, lifelong learner, and weekend guitar enthusiast.',skills:'Design, Guitar, Photography',mode:null};accounts.push(user);S.set('accounts',accounts);seedDemo(user);}signIn(user,false);}
function seedDemo(user){const base=S.get('classes')[2];const mine=[{...base,id:'demo-guitar',ownerId:user.id,instructor:user.name,title:'Basic Guitar for Beginners',price:50000,date:S.day(2),capacity:10,filled:0,students:0,rating:4.8,image:'assets/images/class-2.svg',createdAt:Date.now(),status:'Active'},{...S.get('classes')[0],id:'demo-design-draft',ownerId:user.id,instructor:user.name,title:'Design Your First Portfolio',price:100000,students:0,filled:0,capacity:12,rating:0,date:S.day(7),status:'Draft',createdAt:Date.now()}];S.set('createdClasses',[...S.get('createdClasses'),...mine]);const names=['Nabila Putri','Arif Setiawan','Dewi Lestari','Fajar Pratama','Nadia Sari','Bayu Saputra','Citra Ananda','Raka Putra'];const enrollments=names.map((name,i)=>({id:'demo-student-'+i,userId:'sample-'+i,name,email:'learner'+(i+1)+'@example.com',classId:'demo-guitar',date:S.day(-3),status:'Upcoming',sample:true}));enrollments.push({id:'demo-enrollment',userId:user.id,name:user.name,email:user.email,classId:'figma',date:S.day(-1),status:'Completed',sample:true});S.set('enrollments',[...S.get('enrollments'),...enrollments]);S.set('payments',[...S.get('payments'),...names.map((name,i)=>({id:'DEMO-'+(100+i),userId:'sample-'+i,name,classId:'demo-guitar',date:S.day(-3),price:50000,fee:5000,total:55000,method:'GoPay',status:i<6?'Completed':'Pending',sample:true})),{id:'DEMO-LEARN',userId:user.id,name:user.name,classId:'figma',date:S.day(-1),price:75000,fee:5000,total:80000,method:'DANA',status:'Completed',sample:true}]);S.set('notifications',[...S.get('notifications'),...['Your payment was successful.','Your guitar class starts soon.','Sarah joined your class.','Your class received a new review.','Your class is now 80% full.'].map(text=>({id:S.id(),userId:user.id,text,date:new Date().toISOString(),read:false,sample:true}))]);}
document.querySelector('#demo-login')?.addEventListener('click',demo);
document.querySelector('#google-demo')?.addEventListener('click',()=>{S.modal('Google sign-in simulation','<p>No Google account is connected. Continue with the local Athira demo account to explore both modes.</p><button class="btn full" id="confirm-google" style="margin-bottom:12px">Continue as Athira</button>');document.querySelector('#confirm-google').onclick=demo;});
document.querySelector('#forgot')?.addEventListener('click',()=>S.modal('Password help','<p>This prototype has no email service. For the demo account, use <strong>athira</strong> and <strong>demo123</strong>. For another local account, create a new account with a different email to restart testing.</p>'));
})();
