'use strict';
(() => {
const page=document.body.dataset.page,root=document.querySelector('#page-content');
if(!S.user()){location.replace('../login.html');return;}
S.set('currentMode','instructor');
document.querySelector('#instructor-sidebar')?.insertAdjacentHTML('beforeend',S.sidebar());
const title=(h,sub='Make room for what you love to share.')=>`<div class="page-head" style="padding-top:0"><span class="eyebrow">Instructor workspace</span><h1>${h}</h1><p>${sub}</p></div>`;
const myStudents=(id)=>S.get('enrollments',[]).filter(e=>e.status!=='Cancelled'&&(id?e.classId===id:S.mine().some(c=>c.id===e.classId)));
const myPayments=()=>S.get('payments',[]).filter(p=>S.mine().some(c=>c.id===p.classId));
const net=p=>Math.round(p.price*.9);
const stat=(l,v,n='')=>`<div class="stat"><span>${l}</span><strong>${v}</strong><small>${n}</small></div>`;
function ownClass(){const id=new URLSearchParams(location.search).get('id');const c=S.mine().find(x=>x.id===id);if(!c){root.innerHTML=title('Choose one of your classes.')+S.empty('No class selected.','Open a class from your teaching dashboard.','instructor/my-classes.html','View My Classes');return null;}return c;}
function cancel(id){const c=S.mine().find(x=>x.id===id);if(!c)return;if(!confirm(`Cancel “${c.title}”? Enrollments will be cancelled and prototype payments marked Refunded.`))return;const classes=S.get('createdClasses',[]);classes.find(x=>x.id===id).status='Cancelled';S.set('createdClasses',classes);const enrollments=S.get('enrollments',[]);enrollments.filter(e=>e.classId===id).forEach(e=>e.status='Cancelled');S.set('enrollments',enrollments);const payments=S.get('payments',[]);payments.filter(p=>p.classId===id).forEach(p=>p.status='Refunded');S.set('payments',payments);S.notify(c.title+' was cancelled. Demo refunds were recorded.');location.reload();}
function classTable(classes){return classes.length?`<div class="panel table-wrap" style="padding:0"><table><thead><tr><th>Class</th><th>Price</th><th>Students / Capacity</th><th>Schedule</th><th>Rating</th><th>Status</th><th>Actions</th></tr></thead><tbody>${classes.map(c=>`<tr><td><strong>${S.esc(c.title)}</strong><span class="muted tiny">${c.category} · ${c.type}</span></td><td>${S.money(c.price)}</td><td>${myStudents(c.id).length} / ${c.capacity||'—'}</td><td>${c.date?S.date(c.date):'Not set'}<br><span class="tiny muted">${c.time||''}</span></td><td>${c.rating||'New'} ★</td><td><span class="status ${c.status}">${c.status}</span></td><td><a class="btn small secondary" href="../class-detail.html?id=${c.id}">View</a><a class="btn small secondary" href="create-class.html?id=${c.id}">Edit</a><a class="btn small secondary" href="class-management.html?id=${c.id}">Manage</a><a class="btn small secondary" href="students.html?id=${c.id}">Manage Students</a>${c.status!=='Cancelled'?`<button class="btn small danger" data-cancel="${c.id}">Cancel</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:S.empty('Your next class starts here.','Share a skill and make someone’s day.','instructor/create-class.html','Create New Class');}
function bindCancel(){document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>cancel(b.dataset.cancel));}
if(page==='dashboard'){
const classes=S.mine(),payments=myPayments().filter(p=>p.status==='Completed'),students=myStudents(),rated=classes.filter(c=>c.rating>0);root.innerHTML=title(`Welcome back, ${S.esc(S.user().name.split(' ')[0])} 👋`,'Your knowledge is someone else’s next possibility.')+`<div class="notice">Prototype workspace · Demo accounts contain sample participants and transactions. All totals below are calculated from saved data.</div><div class="stats">${stat('Total Earnings',S.money(payments.reduce((s,p)=>s+net(p),0)),'After 10% platform fee')}${stat('Active Classes',classes.filter(c=>c.status==='Active').length,'Keep sharing what you know')}${stat('Total Students',students.length,'Learning with you')}${stat('Average Rating',rated.length?(rated.reduce((s,c)=>s+c.rating,0)/rated.length).toFixed(1)+' ★':'New','Your community feedback')}</div><div class="actions"><a class="btn" href="create-class.html">＋ Create New Class</a><a class="btn secondary" href="my-classes.html">Manage Classes</a><a class="btn secondary" href="students.html">View Students</a><a class="btn secondary" href="earnings.html">View Earnings</a></div><div class="section-head"><h2>Upcoming Classes</h2></div>${classTable(classes.filter(c=>c.status==='Active').sort((a,b)=>a.date.localeCompare(b.date)))}<section class="panel"><h2>Recent Activity</h2>${S.owned('notifications').slice(0,4).map(n=>`<div class="notification"><span class="dot"></span><div>${S.esc(n.text)}<div class="tiny muted">${new Date(n.date).toLocaleDateString()}</div></div></div>`).join('')||'<p>Your teaching activity will appear here.</p>'}</section>`;bindCancel();
}
if(page==='my-classes'){
let tab=new URLSearchParams(location.search).get('tab')||'Active';root.innerHTML=title('Your skills, out in the world.','Create, refine, and manage the classes you share.')+'<a class="btn" href="create-class.html">＋ Create New Class</a><div class="tabs" id="class-tabs"></div><div id="class-list"></div>';
function render(){document.querySelector('#class-tabs').innerHTML=['Active','Draft','Completed','Cancelled'].map(t=>`<button class="tab ${tab===t?'active':''}" data-status="${t}">${t} (${S.mine().filter(c=>c.status===t).length})</button>`).join('');document.querySelector('#class-list').innerHTML=classTable(S.mine().filter(c=>c.status===tab));document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{tab=b.dataset.status;render();});bindCancel();}render();
}
if(page==='class-management'){
const c=ownClass();if(!c)return;const students=myStudents(c.id),payments=myPayments().filter(p=>p.classId===c.id&&p.status==='Completed');root.innerHTML=title(S.esc(c.title),'Everything you need to keep your class on track.')+`<div class="actions"><a class="btn" href="create-class.html?id=${c.id}">Edit Class</a><a class="btn secondary" href="students.html?id=${c.id}">Manage Students</a>${c.status==='Active'?`<button class="btn secondary" id="complete-class">Mark Class Completed</button>`:''}${!['Cancelled','Completed'].includes(c.status)?`<button class="btn danger" data-cancel="${c.id}">Cancel Class</button>`:''}</div><div class="stats">${stat('Price',S.money(c.price))}${stat('Students / Capacity',students.length+' / '+c.capacity)}${stat('Rating',c.rating||'New')}${stat('Revenue',S.money(payments.reduce((n,p)=>n+net(p),0)))}</div><section class="panel"><h2>Class Information</h2><ul class="detail-list"><li><span>Schedule</span><strong>${S.date(c.date)} · ${c.time}</strong></li><li><span>Type</span><strong>${c.type}</strong></li><li><span>Status</span><strong>${c.status}</strong></li></ul><p>${S.esc(c.description)}</p></section><section class="panel"><h2>Participants</h2>${students.map(e=>`<div class="notification"><span class="avatar">${S.esc(e.name.slice(0,1))}</span><div>${S.esc(e.name)}<div class="tiny muted">${e.status}${e.sample?' · Sample participant':''}</div></div></div>`).join('')||'<p>No participants yet.</p>'}</section><section class="panel"><h2>Reviews</h2>${S.get('reviews',[]).filter(r=>r.classId===c.id).map(r=>`<div class="review-card"><strong>${S.esc(r.name)} · ${r.rating} ★</strong><p>${S.esc(r.text)}</p></div>`).join('')||'<p>No learner reviews yet.</p>'}</section><section class="panel"><h2>Recent Activity</h2><p>Class status: ${c.status}. ${students.length} participant(s) enrolled.</p></section>`;bindCancel();document.querySelector('#complete-class')?.addEventListener('click',()=>{if(!confirm('Mark this class completed for all participants?'))return;const all=S.get('createdClasses',[]);all.find(x=>x.id===c.id).status='Completed';S.set('createdClasses',all);const en=S.get('enrollments',[]);en.filter(e=>e.classId===c.id&&e.status!=='Cancelled').forEach(e=>e.status='Completed');S.set('enrollments',en);S.notify(c.title+' is now completed.');location.reload();});
}
if(page==='students'){
const selectedId=new URLSearchParams(location.search).get('id');const classes=S.mine();const selected=classes.find(c=>c.id===selectedId);const list=myStudents(selected?.id);const capacity=selected?selected.capacity:classes.filter(c=>c.status==='Active').reduce((n,c)=>n+Number(c.capacity||0),0);root.innerHTML=title('Meet your learners.','Small groups. Big possibilities.')+`<form class="results-bar" id="student-filter"><select class="control" name="id" aria-label="Filter by class"><option value="">All your classes</option>${classes.map(c=>`<option value="${c.id}" ${selected?.id===c.id?'selected':''}>${S.esc(c.title)}</option>`).join('')}</select><button class="btn">Filter</button></form><div class="notice">${list.length} / ${capacity} seats filled${selected?' · '+S.esc(selected.title):' across your classes'}</div>${list.length?`<div class="panel table-wrap" style="padding:0"><table><thead><tr><th>Profile</th><th>Name</th><th>Payment Status</th><th>Enrollment Date</th><th>Status</th><th>Actions</th></tr></thead><tbody>${list.map(e=>`<tr><td><span class="avatar">${S.esc(e.name.slice(0,1))}</span></td><td><strong>${S.esc(e.name)}</strong><span class="tiny muted">${e.sample?'Sample participant':'Learner'}</span></td><td><span class="status">${S.get('payments',[]).find(p=>p.userId===e.userId&&p.classId===e.classId)?.status||'Not recorded'}</span></td><td>${S.date(e.date)}</td><td>${e.status}</td><td><button class="btn small secondary" data-student="${e.id}">View Profile</button><button class="btn small secondary" data-contact="${e.id}">Contact</button></td></tr>`).join('')}</tbody></table></div>`:S.empty('Your community starts with one learner.','Participants will appear after enrollment.','instructor/my-classes.html','Manage Classes')}`;
document.querySelectorAll('[data-student]').forEach(b=>b.onclick=()=>{const e=list.find(e=>e.id===b.dataset.student);S.modal(e.name,`<p>Enrolled in ${S.esc(S.find(e.classId)?.title)}.</p><p>Status: ${e.status}<br>Joined: ${S.date(e.date)}</p>${e.sample?'<p>This is a sample participant for usability testing.</p>':''}`);});document.querySelectorAll('[data-contact]').forEach(b=>b.onclick=()=>{const e=list.find(e=>e.id===b.dataset.contact);S.modal('Contact '+e.name,`<p>${e.sample?'Sample email address':'Learner email'}: <strong>${S.esc(e.email)}</strong></p><p>The prototype does not send messages. You can copy this address for your test.</p>`);});
}
if(page==='earnings'){
const payments=myPayments(),paid=payments.filter(p=>p.status==='Completed'),month=S.day(0).slice(0,7),total=paid.reduce((n,p)=>n+net(p),0),monthTotal=paid.filter(p=>p.date.startsWith(month)).reduce((n,p)=>n+net(p),0),pending=payments.filter(p=>p.status==='Pending').reduce((n,p)=>n+net(p),0);const months=Array.from({length:6},(_,i)=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-5+i);const key=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');return{label:d.toLocaleDateString('en',{month:'short'}),value:paid.filter(p=>p.date.startsWith(key)).reduce((n,p)=>n+net(p),0)};});const max=Math.max(1,...months.map(x=>x.value));root.innerHTML=title('Good skills. Well earned.','A clear view of what your knowledge brings in.')+`<div class="stats">${stat('Total Earnings',S.money(total))}${stat('This Month',S.money(monthTotal))}${stat('Pending Balance',S.money(pending))}${stat('Completed Payments',paid.length)}</div><div class="notice">All earnings are simulated. Instructor earnings equal the class price minus a 10% platform fee. The learner’s Rp5.000 checkout fee is separate. Promotional discounts are covered by the prototype platform.</div><section class="panel"><h2>Earnings over time</h2><p class="tiny">Net earnings · Last 6 months</p><div class="chart" role="img" aria-label="${months.map(m=>m.label+': '+S.money(m.value)).join(', ')}">${months.map(m=>`<div class="chart-bar" style="height:${Math.max(2,m.value/max*130)}px"><small>${S.money(m.value)}</small><span>${m.label}</span></div>`).join('')}</div></section><section class="panel"><h2>Transactions</h2>${payments.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Class</th><th>Student</th><th>Net Amount</th><th>Status</th></tr></thead><tbody>${payments.map(p=>`<tr><td>${S.date(p.date)}</td><td>${S.esc(S.find(p.classId)?.title)}</td><td>${S.esc(p.name)}</td><td>${S.money(net(p))}</td><td><span class="status">${p.status}</span></td></tr>`).join('')}</tbody></table></div>`:'<p>Your first earnings start with your first enrollment.</p>'}</section>`;
}
if(page==='create-class'){
const form=document.querySelector('#class-form'),error=document.querySelector('#class-error');const id=new URLSearchParams(location.search).get('id');let edit=id?S.mine().find(c=>c.id===id):null;
if(id&&!edit){form.innerHTML=S.empty('Class not found.','You can only edit your own classes.','instructor/my-classes.html','My Classes');return;}
let step=0,image=edit?.image||'',dirty=false;const draftId=edit?.id||S.id();
if(edit){for(const [key,v]of Object.entries(edit)){const el=form.elements.namedItem(key);if(el&&el.type!=='file')el.value=Array.isArray(v)?v.join('\n'):v;}}
form.elements.date.min=S.day(0);
const fields=()=>Object.fromEntries(new FormData(form));
function classData(status){const d=fields();return {...edit,id:draftId,ownerId:S.uid(),title:d.title.trim()||'Untitled class',category:d.category,level:d.level,short:d.short.trim(),description:d.description.trim(),learn:d.learn.split('\n').map(x=>x.trim()).filter(Boolean),requirements:d.requirements.trim(),date:d.date||S.day(1),time:d.time||'19:00',duration:Number(d.duration),sessions:Number(d.sessions),type:d.type,platform:d.platform,location:d.location.trim(),address:d.address.trim(),capacity:Number(d.capacity),price:Number(d.price),instructor:S.user().name,bio:S.user().bio||'A passionate community instructor sharing practical skills.',image:image||'assets/images/class-'+({'Design':0,'Photography':1,'Music':2,'Programming':3,'Business':4,'Marketing':5,'Language':6,'Cooking':7}[d.category])+'.svg',filled:0,students:edit?.students||0,rating:edit?.rating||0,status,createdAt:edit?.createdAt||Date.now()};}
function render(){document.querySelectorAll('.wizard-step').forEach((el,i)=>el.hidden=i!==step);document.querySelectorAll('#wizard-progress span').forEach((el,i)=>el.classList.toggle('active',i<=step));document.querySelector('#wizard-back').hidden=step===0;document.querySelector('#wizard-next').hidden=step===6;document.querySelector('#publish').hidden=step!==6;error.textContent='';if(step===6){const c=classData('Active');document.querySelector('#class-preview').innerHTML=S.details(c)+`<div class="panel"><span class="price">${S.money(c.price)}</span><p>${c.capacity} available seats · ${c.type}</p><p>Instructor: ${S.esc(c.instructor)}</p><span class="btn">Join Class — ${S.money(c.price)} (Preview)</span></div>`;}}
function validStep(i){const controls=document.querySelector(`.wizard-step[data-step="${i}"]`).querySelectorAll('input,select,textarea');for(const el of controls){if(!el.checkValidity()){step=i;render();error.textContent=el.name==='price'?'Please set a class price before publishing.':'Please complete the required fields correctly.';el.reportValidity();return false;}}if(i===4&&+form.elements.capacity.value<myStudents(draftId).length){step=4;render();error.textContent='Capacity cannot be lower than the current participant count.';return false;}return true;}
function save(status){const c=classData(status),all=S.get('createdClasses',[]),index=all.findIndex(x=>x.id===draftId);if(index>=0)all[index]=c;else all.push(c);if(!S.set('createdClasses',all))return;dirty=false;S.notify(status==='Draft'?'Your class draft was saved.':(edit?'Your class was updated.':'Your class is now published: '+c.title+'.'));location.href='my-classes.html?tab='+status;}
document.querySelector('#wizard-next').onclick=()=>{if(validStep(step)){step++;render();window.scrollTo({top:0,behavior:'smooth'});}};document.querySelector('#wizard-back').onclick=()=>{step--;render();};document.querySelector('#save-draft').onclick=()=>{if(edit?.status==='Active'&&myStudents(edit.id).length){S.toast('This class has participants. Publish your edits to update it.');return;}save('Draft');};
form.noValidate=true;form.onsubmit=e=>{e.preventDefault();for(let i=0;i<6;i++)if(!validStep(i))return;save('Active');};form.addEventListener('input',()=>dirty=true);
function typeChange(){const offline=form.elements.type.value==='Offline';document.querySelector('#online-fields').hidden=offline;document.querySelector('#offline-fields').hidden=!offline;form.elements.location.required=offline;form.elements.address.required=offline;}form.elements.type.onchange=typeChange;typeChange();
form.elements.capacity.oninput=()=>document.querySelector('#capacity-label').textContent=myStudents(draftId).length+' / '+form.elements.capacity.value+' seats filled';form.elements.capacity.oninput();
function calc(){const p=+form.elements.price.value;document.querySelector('#calc-price').textContent=S.money(p);document.querySelector('#calc-fee').textContent=S.money(Math.round(p*.1));document.querySelector('#calc-net').textContent=S.money(Math.round(p*.9))+' / participant';}form.elements.price.oninput=calc;calc();
form.elements.thumbnail.onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>2*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type)){error.textContent='Please choose a PNG, JPG, or WebP image under 2 MB.';e.target.value='';return;}const reader=new FileReader();reader.onload=()=>{image=reader.result;const img=document.querySelector('#thumbnail-preview');img.src=image;img.hidden=false;};reader.readAsDataURL(file);};if(image){const img=document.querySelector('#thumbnail-preview');img.src=S.image(edit);img.hidden=false;}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});render();
}
})();
