'use strict';
(() => {
const page=document.body.dataset.page,root=document.querySelector('#page-content');
const title=(heading,sub='',tag='Your next chapter')=>`<div class="page-head"><span class="eyebrow">${tag}</span><h1>${heading}</h1><p>${sub}</p></div>`;
const publicClasses=()=>S.all().filter(c=>c.status==='Active');
function needUser(){if(S.user())return true;root.innerHTML=title('Make yourself at home.')+S.empty('Sign in to continue','Your classes, payments, and profile live in your account.','login.html','Sign In');return false;}
function getClass(){const id=new URLSearchParams(location.search).get('id');const c=S.find(id||'figma');if(!c){root.innerHTML=title('Class not found')+S.empty('This class is no longer available.','Find another skill to explore.','explore.html','Explore Classes');return null;}return c;}
function enrolled(c){return S.owned('enrollments').find(e=>e.classId===c.id&&e.status!=='Cancelled');}
function filled(c){return (c.filled||0)+S.get('enrollments',[]).filter(e=>e.classId===c.id&&e.status!=='Cancelled').length;}
if(page==='index'){
document.querySelector('#categories').innerHTML=S.categories.map((c,i)=>`<a class="category" data-category="${c}" href="explore.html?category=${c}"><span class="cat-icon">${S.icons[i]}</span>${c}</a>`).join('');document.querySelector('#popular-classes').innerHTML=publicClasses().slice(0,3).map(S.card).join('');
if(S.user()){document.querySelector('#landing-hero').hidden=true;const w=document.querySelector('#learner-welcome');w.hidden=false;w.innerHTML=title(`Hi, ${S.esc(S.user().name.split(' ')[0])} 👋`,'What will you discover today?','Your learning journey')+'<form class="searchbox" action="explore.html"><input name="q" placeholder="What do you want to learn?" aria-label="What do you want to learn?"><button class="btn">Find a class ↗</button></form><a class="btn secondary" href="my-learning.html">View My Learning →</a>';document.querySelector('#popular-title').textContent='Recommended For You';}
}
if(page==='explore'){
let category=new URLSearchParams(location.search).get('category')||'All',applied={};const search=document.querySelector('#search');search.value=new URLSearchParams(location.search).get('q')||'';
const filter=document.querySelector('#filters');
function render(){const q=search.value.trim().toLowerCase();let list=publicClasses().filter(c=>(category==='All'||c.category===category)&&[c.title,c.category,c.instructor].join(' ').toLowerCase().includes(q));
list=list.filter(c=>(!applied.min||c.price>=Number(applied.min))&&(!applied.max||c.price<=Number(applied.max))&&(!['4+ stars','3+ stars'].includes(applied.rating)||c.rating>=parseInt(applied.rating))&&(!applied.level||applied.level==='All levels'||c.level===applied.level)&&(!applied.type||applied.type==='All types'||c.type===applied.type)&&(!(applied.type==='Offline'&&applied.location)||c.location.toLowerCase().includes(applied.location.toLowerCase())));
list=list.filter(c=>{const d=new Date(c.date+'T00:00:00'),today=new Date(S.day(0)+'T00:00:00'),delta=Math.round((d-today)/86400000);switch(applied.schedule){case'Today':return delta===0;case'Tomorrow':return delta===1;case'This Week':return delta>=0&&delta<=6-((today.getDay()+6)%7);case'Weekend':return delta>=0&&delta<=7&&[0,6].includes(d.getDay());default:return true;}});
const sort=document.querySelector('#sort').value;list.sort((a,b)=>sort==='Lowest Price'?a.price-b.price:sort==='Highest Rating'?b.rating-a.rating:sort==='Most Popular'?b.students-a.students:sort==='Newest'?b.createdAt-a.createdAt:0);
document.querySelector('#result-count').textContent=`${list.length} ${list.length===1?'class':'classes'} found`;
document.querySelector('#class-grid').innerHTML=list.length?list.map(S.card).join(''):S.empty('No classes found.','Try adjusting your search or filters.');
document.querySelector('#category-tabs').innerHTML=['All',...S.categories].map(c=>`<button class="tab ${c===category?'active':''}" data-category="${c}">${c}</button>`).join('');}
document.querySelector('#category-tabs').onclick=e=>{if(e.target.dataset.category){category=e.target.dataset.category;render();}};
document.querySelector('#search-form').onsubmit=e=>{e.preventDefault();render();};search.oninput=render;document.querySelector('#sort').onchange=render;
filter.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(filter));const er=document.querySelector('#filter-error');if(d.min&&d.max&&+d.min>+d.max){er.textContent='Minimum price must not exceed maximum price.';return;}er.textContent='';applied=d;render();};filter.onreset=()=>{applied={};category='All';search.value='';document.querySelector('#filter-error').textContent='';document.querySelector('#location-filter').hidden=true;setTimeout(render,0);};document.querySelector('#filter-type').onchange=e=>{document.querySelector('#location-filter').hidden=e.target.value!=='Offline';};render();
}
if(page==='class-detail'){
const c=getClass();if(!c)return;const unavailable=c.status!=='Active'||filled(c)>=c.capacity;
root.innerHTML=`<div class="page-head"><div class="breadcrumb"><a href="index.html">Home</a> / <a href="explore.html">Explore Classes</a> / ${S.esc(c.category)}</div></div><div class="two-col"><div>${S.details(c)}<section class="panel"><h2>About The Instructor</h2><div class="profile-hero"><div class="avatar">${S.esc(c.instructor.slice(0,1))}</div><div><h3>${S.esc(c.instructor)} <span class="verified">${c.ownerId?'':'✓'}</span></h3><p>${S.esc(c.bio||'A passionate SkillSwap community instructor.')}</p><p class="tiny">${S.esc(c.category)} · ★ ${c.rating||'New'} · ${c.students||0} students</p><a class="btn secondary" href="instructor-profile.html?id=${encodeURIComponent(c.id)}">View Instructor Profile ↗</a></div></div></section><section class="panel"><h2>Student Reviews</h2>${S.reviewHTML(c.id)}</section></div><aside class="panel sticky"><span class="badge">${S.esc(c.type)} workshop</span><h2 style="margin-top:18px">A small step.<br>A new possibility.</h2><p>Learn directly. Ask questions. Make something.</p><div class="price" style="font-size:32px">${S.money(c.price)} <span class="tiny muted">/ person</span></div><ul class="detail-list"><li><span>Date</span><strong>${S.date(c.date)}</strong></li><li><span>Time</span><strong>${c.time}</strong></li><li><span>Duration</span><strong>${c.duration} minutes</strong></li><li><span>Level</span><strong>${S.esc(c.level)}</strong></li><li><span>Available seats</span><strong>${Math.max(0,c.capacity-filled(c))} of ${c.capacity}</strong></li></ul>${enrolled(c)?'<a class="btn full" href="my-learning.html">View My Learning →</a>':unavailable?'<div class="notice">This class is currently '+(c.status==='Active'?'full.':'unavailable.')+'</div>':`<a class="btn full" href="checkout.html?id=${encodeURIComponent(c.id)}">Join Class — ${S.money(c.price)}</a>`}<div class="actions"><button class="btn secondary" id="bookmark">♡ Save</button><button class="btn secondary" id="share">↗ Share</button></div><div class="tiny muted center">Secure simulated checkout · No real charge</div></aside></div>`;
const save=document.querySelector('#bookmark');function saved(){return S.owned('bookmarks').some(b=>b.classId===c.id);}function label(){save.textContent=saved()?'♥ Saved':'♡ Save';}label();save.onclick=()=>{if(!S.user()){location.href='login.html';return;}let b=S.get('bookmarks',[]);if(saved())b=b.filter(x=>!(x.userId===S.uid()&&x.classId===c.id));else b.push({userId:S.uid(),classId:c.id});if(S.set('bookmarks',b))label();};document.querySelector('#share').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);S.toast('Class link copied.');}catch{S.modal('Share this class',`<label class="field">Copy this link<input readonly value="${S.esc(location.href)}"></label>`);}};
}
if(page==='instructor-profile'){
const c=getClass();if(!c)return;const list=publicClasses().filter(x=>x.instructor===c.instructor);root.innerHTML=title('Meet your instructor.','Real experience, shared with you.');root.innerHTML+=`<div class="panel"><div class="profile-hero"><div class="avatar">${S.esc(c.instructor.slice(0,1))}</div><div><h1>${S.esc(c.instructor)} <span class="verified">${c.ownerId?'':'✓'}</span></h1><p>${S.esc(c.bio||'Passionate about sharing practical skills with curious people.')}</p><span class="badge">${S.esc(c.category)}</span></div></div><div class="stats">${[['Rating',c.rating||'New'],['Total Students',list.reduce((n,x)=>n+x.students,0)],['Classes',list.length],['Reviews',S.reviews(c.id).length]].map(([l,v])=>`<div class="stat"><span>${l}</span><strong>${v}</strong></div>`).join('')}</div><div class="tabs"><button class="tab active" data-tab="about">About</button><button class="tab" data-tab="classes">Classes</button><button class="tab" data-tab="reviews">Reviews</button></div><div id="profile-tab"></div></div>`;
const render=tab=>{document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelector('#profile-tab').innerHTML=tab==='classes'?`<div class="grid">${list.map(S.card).join('')}</div>`:tab==='reviews'?S.reviewHTML(c.id):`<h2>A practical approach to learning.</h2><p>${S.esc(c.bio||'I believe the best way to learn is to create something, ask questions, and enjoy the process.')}</p><p>Skills: ${S.esc(c.category)}</p><a class="btn" href="class-detail.html?id=${encodeURIComponent(c.id)}">Explore this class ↗</a>`;};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>render(b.dataset.tab));render('about');
}
if(page==='checkout'){
if(!needUser())return;const c=getClass();if(!c)return;if(enrolled(c)){root.innerHTML=title('You’re already enrolled.')+S.empty('Your seat is waiting.','Find this class in My Learning.','my-learning.html','View My Learning');return;}if(c.ownerId===S.uid()){root.innerHTML=title('This is your class.')+S.empty('Manage your class in Teach Mode.','You cannot purchase your own class.','instructor/class-management.html?id='+c.id,'Manage Class');return;}if(c.status!=='Active'||filled(c)>=c.capacity){root.innerHTML=title('This class is currently full or unavailable.')+S.empty('Find your next class.','Explore more practical workshops.','explore.html','Explore Classes');return;}
let discount=0;const fee=5000;root.innerHTML=title('You’re one step closer.','A new skill is a pretty good investment.','Checkout')+`<form id="checkout-form" class="two-col"><div><div class="panel"><h2>Your class</h2><div class="learning-card"><img src="${S.image(c)}" alt="Class illustration"><div><span class="badge">${c.category}</span><h3>${S.esc(c.title)}</h3><p>${S.esc(c.instructor)}</p><div class="tiny muted">${S.date(c.date)} · ${c.time}<br>${c.type} · ${c.duration} minutes</div></div></div></div><div class="panel"><h2>Choose a payment method</h2><p>Demo checkout. No real payment information needed.</p>${['GoPay','OVO','DANA','Bank Transfer','Credit/Debit Card'].map((m,i)=>`<label class="payment-option"><input type="radio" name="method" value="${m}" ${i===0?'checked':''} required><strong>${m}</strong></label>`).join('')}<label class="tiny"><input type="checkbox" id="simulate-failure"> Simulate payment failure (usability test)</label></div></div><aside class="panel sticky"><h2>Order Summary</h2><ul class="detail-list"><li><span>Class Price</span><strong>${S.money(c.price)}</strong></li><li><span>Platform Fee</span><strong>${S.money(fee)}</strong></li><li><span>Promo Discount</span><strong id="discount">Rp0</strong></li><li><strong>Total</strong><strong id="total">${S.money(c.price+fee)}</strong></li></ul><label class="field">Promo Code<input id="promo" placeholder="Enter promo code"></label><button type="button" class="btn secondary full" id="apply-promo">Apply code</button><p class="tiny muted">Try LEARN10 for 10% off the class price.</p><div class="form-error" id="payment-error" role="alert"></div><button class="btn full" id="pay">Pay ${S.money(c.price+fee)}</button><p class="tiny center">Simulated payment · Nothing will be charged</p></aside></form>`;
document.querySelector('#apply-promo').onclick=()=>{discount=document.querySelector('#promo').value.trim().toUpperCase()==='LEARN10'?Math.round(c.price*.1):0;document.querySelector('#discount').textContent='−'+S.money(discount);document.querySelector('#total').textContent=S.money(c.price+fee-discount);document.querySelector('#pay').textContent='Pay '+S.money(c.price+fee-discount);S.toast(discount?'Promo applied.':'That promo code is not valid.');};
document.querySelector('#checkout-form').onsubmit=e=>{e.preventDefault();const pay=document.querySelector('#pay');pay.disabled=true;pay.textContent='Processing payment…';document.querySelector('#payment-error').textContent='';setTimeout(()=>{if(document.querySelector('#simulate-failure').checked){document.querySelector('#payment-error').textContent='Payment failed. Please try another payment method.';pay.disabled=false;pay.textContent='Pay '+S.money(c.price+fee-discount);return;}if(enrolled(c)||filled(c)>=c.capacity||S.find(c.id).status!=='Active'){S.toast('Class availability changed. Please reload this page.');pay.disabled=false;return;}const payment={id:'SS-'+S.id().slice(0,8).toUpperCase(),userId:S.uid(),name:S.user().name,classId:c.id,date:S.day(0),price:c.price,fee,total:c.price+fee-discount,discount,method:new FormData(e.target).get('method'),status:'Completed'};const enroll={id:S.id(),userId:S.uid(),name:S.user().name,email:S.user().email,classId:c.id,date:S.day(0),status:'Upcoming'};const before=S.get('payments',[]);if(!S.set('payments',[...before,payment])){pay.disabled=false;return;}if(!S.set('enrollments',[...S.get('enrollments',[]),enroll])){S.set('payments',before);pay.disabled=false;return;}S.notify('Your payment was successful. You joined '+c.title+'.');location.href='payment-success.html?order='+encodeURIComponent(payment.id);},800);};
}
if(page==='payment-success'){
if(!needUser())return;const order=new URLSearchParams(location.search).get('order');const p=S.owned('payments').find(x=>x.id===order);if(!p){root.innerHTML=title('No payment found.')+S.empty('Your purchases will appear here.','Explore classes to start learning.','explore.html','Explore Classes');return;}const c=S.find(p.classId);root.innerHTML=`<div class="success-page"><div class="panel"><div class="success-icon">✓</div><div class="center"><span class="eyebrow">Your next chapter is booked</span><h1>Payment Successful!</h1><p>You are successfully enrolled in this class.</p></div><ul class="detail-list"><li><span>Class</span><strong>${S.esc(c.title)}</strong></li><li><span>Instructor</span><strong>${S.esc(c.instructor)}</strong></li><li><span>Schedule</span><strong>${S.date(c.date)} · ${c.time}</strong></li><li><span>Order ID</span><strong>${S.esc(p.id)}</strong></li><li><span>Amount Paid</span><strong>${S.money(p.total)}</strong></li></ul><div class="notice">Simulated transaction. No money was charged.</div><a class="btn full" href="my-learning.html">View My Learning →</a><a class="btn ghost full" href="index.html">Back to Home</a></div></div>`;
}
if(page==='my-learning'){
if(!needUser())return;let tab=new URLSearchParams(location.search).get('tab')||'All';root.innerHTML=title('Keep your curiosity going.','Your classes, your progress, your next big thing.','My Learning')+'<div class="dashboard"><aside class="sidebar" id="learning-tabs"></aside><section id="learning-content"></section></div>';
function render(){const tabs=['All','Upcoming','In Progress','Completed','Payment History'];document.querySelector('#learning-tabs').innerHTML=tabs.map(t=>`<a href="?tab=${encodeURIComponent(t)}" data-tab="${t}" class="${t===tab?'active':''}">${t==='All'?'My Learning':t}</a>`).join('');const el=document.querySelector('#learning-content');if(tab==='Payment History'){const payments=S.owned('payments');el.innerHTML='<h2>Payment History</h2>'+(payments.length?`<div class="panel table-wrap"><table><thead><tr><th>Order</th><th>Class</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>${payments.map(p=>`<tr><td><a class="verified" href="payment-success.html?order=${p.id}">${p.id}</a></td><td>${S.esc(S.find(p.classId)?.title||'Unavailable class')}</td><td>${S.date(p.date)}</td><td>${S.money(p.total)}</td><td>${p.status}</td></tr>`).join('')}</tbody></table></div>`:S.empty('No payments yet.','Your simulated payment history will appear here.'));}else{const list=S.owned('enrollments').filter(e=>tab==='All'||e.status===tab);el.innerHTML=`<h2>${tab==='All'?'Your classes':tab+' Classes'}</h2><p class="tiny muted">Use the demo session controls to test joining, completion, and reviews.</p>`+(list.length?list.map(e=>{const c=S.find(e.classId);if(!c)return'';return `<article class="panel learning-card"><img src="${S.image(c)}" alt="${S.esc(c.category)} illustration"><div class="grow"><span class="badge">${e.status}</span><h3><a href="class-detail.html?id=${c.id}">${S.esc(c.title)}</a></h3><p>${S.esc(c.instructor)}</p><div class="tiny muted">${S.date(c.date)} · ${c.time}</div></div><div>${e.status==='Completed'?`<a class="btn secondary" href="review.html?id=${c.id}">Leave Review</a>`:e.status==='Cancelled'?'<span class="muted">Cancelled</span>':`<button class="btn" data-session="${e.id}">${e.status==='Upcoming'?'Join Demo Session':'Complete Demo Session'}</button>`}</div></article>`;}).join(''):S.empty('Your next skill is waiting.','Find a class and take the first step.','explore.html','Explore Classes'));}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=e=>{e.preventDefault();tab=b.dataset.tab;history.replaceState(null,'','?tab='+encodeURIComponent(tab));render();});document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>{const all=S.get('enrollments',[]);const en=all.find(x=>x.id===b.dataset.session&&x.userId===S.uid());if(en){en.status=en.status==='Upcoming'?'In Progress':'Completed';if(S.set('enrollments',all)){S.toast(en.status==='Completed'?'Class completed. Share your experience!':'Demo session started. No real meeting is opened.');render();}}});}render();
}
if(page==='review'){
if(!needUser())return;const c=getClass();if(!c)return;const en=enrolled(c);if(en?.status!=='Completed'){root.innerHTML=title('Finish your class first.')+S.empty('Reviews come after learning.','Complete the demo session in My Learning to leave a review.','my-learning.html','View My Learning');return;}const old=S.owned('reviews').find(r=>r.classId===c.id);root.innerHTML=`<div class="success-page">${title('How was your experience?',S.esc(c.title),'Your voice matters')}<form class="panel" id="review-form"><p>Help the next learner find their perfect class.</p><fieldset style="border:0;padding:0"><legend class="tiny">Choose a rating</legend><div class="rating-input">${[1,2,3,4,5].map(n=>`<label><input type="radio" name="rating" value="${n}" required ${n===old?.rating?'checked':''} aria-label="${n} stars">★</label>`).join('')}</div></fieldset><label class="field">Tell us about your experience...<textarea name="text" required minlength="10" maxlength="2000">${S.esc(old?.text||'')}</textarea></label><button class="btn full">${old?'Update':'Submit'} Review</button></form></div>`;function paint(){const v=Number(document.querySelector('[name=rating]:checked')?.value||0);document.querySelectorAll('.rating-input label').forEach((l,i)=>l.classList.toggle('selected',i<v));}paint();document.querySelectorAll('[name=rating]').forEach(i=>i.onchange=paint);document.querySelector('#review-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);const r={id:old?.id||S.id(),userId:S.uid(),classId:c.id,name:S.user().name,rating:Number(d.get('rating')),text:d.get('text').trim(),date:S.day(0)};const all=S.get('reviews',[]).filter(x=>x.id!==r.id);if(S.set('reviews',[r,...all])){S.notify('Your review for '+c.title+' was published.');location.href='class-detail.html?id='+c.id;}};
}
if(page==='profile'){
if(!needUser())return;const u=S.user();root.innerHTML=title('Your space to grow.','One account. Everything you learn and share.','Your Profile')+`<div class="two-col"><div><section class="panel"><div class="profile-hero"><div class="avatar">${S.esc(u.name.slice(0,1))}</div><div><h1>${S.esc(u.name)}</h1><p>${S.esc(u.bio||'Curious learner. Future teacher.')}</p><span class="badge">${S.esc(u.skills||'Add your skills in settings')}</span></div></div><div class="stats">${[['Classes Joined',S.owned('enrollments').length],['Classes Created',S.mine().length],['Students Taught',S.get('enrollments',[]).filter(e=>S.mine().some(c=>c.id===e.classId)).length],['Reviews',S.owned('reviews').length]].map(([l,n])=>`<div class="stat"><span>${l}</span><strong>${n}</strong></div>`).join('')}</div><div class="actions"><button class="btn" data-mode="learner">Switch to Learn Mode</button><button class="btn secondary" data-mode="instructor">Switch to Teach Mode</button></div></section><form class="panel" id="profile-form"><h2>Profile Settings</h2><label class="field">Name<input name="name" value="${S.esc(u.name)}" required maxlength="70"></label><label class="field">Bio<textarea name="bio" maxlength="500">${S.esc(u.bio||'')}</textarea></label><label class="field">Skills<input name="skills" value="${S.esc(u.skills||'')}" maxlength="150"></label><button class="btn">Save Profile</button></form><section class="panel"><h2>Your Reviews</h2>${S.owned('reviews').map(r=>`<div class="review-card"><strong>${S.esc(S.find(r.classId)?.title)}</strong><p>${S.esc(r.text)}</p><a class="verified" href="review.html?id=${r.classId}">Edit review →</a></div>`).join('')||'<p>No reviews yet. Complete a class to share your experience.</p>'}</section><section><h2>Saved Classes</h2><div class="grid">${S.owned('bookmarks').map(b=>S.find(b.classId)).filter(Boolean).map(S.card).join('')||'<p>You haven’t saved any classes yet.</p>'}</div></section></div><aside class="panel sticky"><h2>Your account</h2><div class="sidebar" style="border:0">${[['my-learning.html','My Learning'],['instructor/my-classes.html','My Classes'],['my-learning.html?tab=Payment%20History','Payment History'],['instructor/earnings.html','Earnings'],['my-learning.html?tab=Completed','Reviews'],['notifications.html','Notifications']].map(([f,t])=>`<a href="${f}">${t} →</a>`).join('')}<button class="btn ghost" id="settings">Settings</button><br><button class="btn danger" id="logout">Logout</button></div></aside></div>`;
document.querySelector('#settings').onclick=()=>document.querySelector('#profile-form input').focus();document.querySelector('#profile-form').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));Object.assign(u,d);if(S.set('user',u)){const accounts=S.get('accounts',[]);const a=accounts.find(x=>x.id===u.id);if(a)Object.assign(a,d);S.set('accounts',accounts);const classes=S.get('createdClasses',[]);classes.filter(c=>c.ownerId===u.id).forEach(c=>c.instructor=u.name);S.set('createdClasses',classes);S.toast('Profile saved.');}};document.querySelector('#logout').onclick=()=>{localStorage.removeItem('user');location.href='index.html';};
}
if(page==='notifications'){
if(!needUser())return;function render(){const n=S.owned('notifications');root.innerHTML=title('You’re in the loop.','Updates from your learning and teaching journey.','Notifications')+'<button class="btn secondary" id="mark-read">Mark all as read</button><section class="panel" style="margin-top:20px">'+(n.length?n.map(x=>`<article class="notification ${x.read?'read':''}"><span class="dot"></span><div><strong>${S.esc(x.text)}</strong><div class="tiny muted">${new Date(x.date).toLocaleString()}${x.sample?' · Demo notification':''}</div></div></article>`).join(''):S.empty('All caught up.','New activity will appear here.'))+'</section>';document.querySelector('#mark-read').onclick=()=>{const all=S.get('notifications',[]);all.filter(x=>x.userId===S.uid()).forEach(x=>x.read=true);S.set('notifications',all);render();};}render();
}
})();
